### ISSUE TITLE
Console error "name 'f0_extractor' is not defined"

### ISSUE THREAD

**Issue by Lordmau5** [yxlllc/DDSP-SVC#110]
So I wrote a small helper Python script a longer while back and updated it so it would fit a better folder structure.
For some reason I misspelled one of the pitch extraction methods and came across this issue in the console:
![image](https://github.com/yxlllc/DDSP-SVC/assets/1345036/ed5138aa-3daf-449e-a5a5-670855af41bf)

Looking at the line and the surrounding code here, it seems it's not using `self.f0_extractor` and thus doesn't print it properly
https://github.com/yxlllc/DDSP-SVC/blob/master/ddsp/vocoder.py#L136

Since it's a single line I thought I'd bring it to your attention since I don't think a PR for a single line would be necessary :)
(And even then it's in my opinion good to track this as a small issue anyway)

**Comment by yxlllc** [comment]
it's rmvpe not rvmpe...

**Comment by yxlllc** [comment]
Thanks for pointing it out, it has been fixed
