### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by francqz31** [yxlllc/DDSP-SVC#2]
Hello author, Thank you for the work if you don't mind I would like to listen to one of the samples if there are any of them , I would like to hear the best quality ones that came out of that algorithm.

Thanks in advance.

**Comment by dillfrescott** [comment]
I would also like to hear the quality before spending the time and computational resources required to train a model.

**Comment by yxlllc** [comment]
Thanks to you suggestion, I have already release a pretrained model and some samples

**Comment by dillfrescott** [comment]
Wow! The enhanced quality is really damn good!

**Comment by dillfrescott** [comment]
@yxlllc also, thank you for the training speedup! It helps a lot!
