### ISSUE TITLE
CUDA out of Memory Error

### ISSUE THREAD

**Issue by jackson55555** [yxlllc/DDSP-SVC#30]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.66 GiB (GPU 0; 8.00 GiB total capacity; 809.64 MiB already allocated; 5.02 GiB free; 1.18 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Thank you for wonderful program! But i have this problem. Can you teach me how to fix it?

**Comment by tarepan** [comment]
`README.md` will help you.

> NOTE 2: ... If there are too many audio clips, you need a large internal-memory or set the 'cache_all_data' option to false in the configuration file.
