### ISSUE TITLE
未来是否会支持cn_hubert，以改善标注？

### ISSUE THREAD

**Issue by fatinghenji** [yxlllc/DDSP-SVC#33]
地址：[chinese_speech_pretrain 汉语语音预训练](https://github.com/TencentGameMate/chinese_speech_pretrain)

**Comment by ms903x1** [comment]
如果你想临时用的话，可以用contentvec加载cn_hubert，将encoder_ckpt:路径改成cn_hubert的就行。

**Comment by KakaruHayate** [comment]
在https://github.com/yxlllc/DDSP-SVC/commit/f3d88b946de5e0448b478151602e8c403b48c03d已获得支持

**Comment by fatinghenji** [comment]
好的，关闭

**Comment by fatinghenji** [comment]
补充询问：在[chinese_speech_pretrain 汉语语音预训练](https://github.com/TencentGameMate/chinese_speech_pretrain)中，共提供了`chinese-wav2vec2-base`、`chinese-wav2vec2-large`、`chinese-hubert-base`、`chinese-hubert-base`四个模型，在本项目中，应当选择哪个模型呢？

**Comment by ms903x1** [comment]
> 补充询问：在[chinese_speech_pretrain 汉语语音预训练](https://github.com/TencentGameMate/chinese_speech_pretrain)中，共提供了、、、四个模型，在本项目中，应当选择哪个模型呢？`chinese-wav2vec2-base``chinese-wav2vec2-large``chinese-hubert-base``chinese-hubert-base`

只支持chinese-hubert-base
