### ISSUE TITLE
change voice fail by command

### ISSUE THREAD

**Issue by shuxiang** [yxlllc/DDSP-SVC#37]
I use command to convert wav files，sounds is change，but not change to chino's voice, did I miss anything?  this is command:

`cd F:\sd-webui\DDSP\DDSP-SVC; ./runtime/Scripts/activate.bat; ./runtime/python.exe main.py -i F:\sd-webui\DDSP\test\test.wav -m exp/model_chino.pt -o F:\sd-webui\DDSP\test\chino.wav -k 0 -id 1 -e true -eak 0`

output:
`
2023-04-17 10:05:36 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX

 [DDSP Model] Combtooth Subtractive Synthesiser

 [Loading] exp/model_chino.pt

Pitch extractor type: crepe

Extracting the pitch curve of the input audio...

Extracting the volume envelope of the input audio...

 [Encoder Model] HuBERT Soft

 [Loading] pretrain/hubert/hubert-soft-0d54a1f4.pt

Enhancer type: nsf-hifigan

| Load HifiGAN:  pretrain/nsf_hifigan/model

Removing weight norm...

Speaker ID: 1

Cut the input audio into 2 slices

100%
`

this command fail too,
`cd F:\sd-webui\DDSP\DDSP-SVC; ./runtime/Scripts/activate.bat; ./runtime/python.exe main.py -i F:\sd-webui\DDSP\test\test.wav -m exp/model_chino.pt -o F:\sd-webui\DDSP\test\chino.wav -k 0 -id 1 -e false`

output:
`
2023-04-17 10:07:58 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX

 [DDSP Model] Combtooth Subtractive Synthesiser

 [Loading] exp/model_chino.pt

Pitch extractor type: crepe

Extracting the pitch curve of the input audio...

Extracting the volume envelope of the input audio...

 [Encoder Model] HuBERT Soft

 [Loading] pretrain/hubert/hubert-soft-0d54a1f4.pt

Enhancer type: none (using raw output of ddsp)

Speaker ID: 1

Cut the input audio into 2 slices

100%
`

**Comment by yxlllc** [comment]
What type of input did you use? If the input is a male voice and the target is a female voice, it is best to use the -k parameter to raise the key

**Comment by shuxiang** [comment]
> 

thanks, I got the point.
