### ISSUE TITLE
Every 2000 steps during DDSP-SVC learning This error occurs.

### ISSUE THREAD

**Issue by anteaterst** [yxlllc/DDSP-SVC#38]
![image](https://user-images.githubusercontent.com/67631822/232719188-84e77997-d3e5-4458-a8b8-8ce1b75e173f.png)

Every 2000 steps during DDSP-SVC learning This error occurs.
I reinstalled the closing torch and Xformers.
Could the above be the cause of the error?

**Comment by yxlllc** [comment]
Did you set up a validation set and perform preprocessing correctly？

**Comment by anteaterst** [comment]
Thank you for your advice.

I'll try again as you said.
