### ISSUE TITLE
速通版Colab（停止更新）

### ISSUE THREAD

**Issue by KakaruHayate** [yxlllc/DDSP-SVC#4]
[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1fK08FGlSwEduD9LDvrRJgkhYJPz37f6u?usp=sharing)

**Comment by KakaruHayate** [comment]
[https://colab.research.google.com/drive/1fK08FGlSwEduD9LDvrRJgkhYJPz37f6u?usp=sharing](https://colab.research.google.com/drive/1fK08FGlSwEduD9LDvrRJgkhYJPz37f6u?usp=sharing)

**Comment by fatinghenji** [comment]
佬，速通版有遇到[这里](https://github.com/yxlllc/DDSP-SVC/issues/16)的报错吗？我是按照您在colab里面写的步骤在本地进行训练的。

**Comment by KakaruHayate** [comment]
> 佬，速通版有遇到[这里](https://github.com/yxlllc/DDSP-SVC/issues/16)的报错吗？我是按照您在colab里面写的步骤在本地进行训练的。

**首先文档中并没有介绍加载预训练模型训练的情况**，我也只验证了早些时候版本加载预训练模型加速收敛的有效性，Colab的代码一些新的地方我也没过测试，**如果是Colab相关的问题还请归在这个issue下**。以下是关于你提的问题的解答：

 - 使用Colab的步骤直接应用到自己的环境上是不合理的，Colab本身就是个预配置过的环境，直接套用可能会出现预料之外的问题，请以本仓库的文档为主结合你的实际情况修改步骤
 - 在Colab中提到了修改`n_spk`参数适配预训练模型，你提交的config并没有进行修改，针对于本仓库release中的sample，这个值你应该改为2
 
![图片](https://user-images.githubusercontent.com/97896816/229330650-a971bc6e-6b10-4a36-8ffd-4d042f13bf3a.png)

 - 此外对于`n_spk>1`的情况，你应该修改你的数据文件结构为多说话人的情况。在Colab的文本中修改说话人参数的文本在很后面，但多说话人相关的描述在开头，这不合理，我会修改

**Comment by fatinghenji** [comment]
感谢您做出的解答！

**Comment by easontet** [comment]
从云盘获取数据集 那邊後面就不會了@@

**Comment by KakaruHayate** [comment]
> 从云盘获取数据集 那邊後面就不會了@@

那个抽卡脚本是用ChatGPT随便写的，有点bug，例如你用多说话人的文件结构，但是根目录下没有wav文件就会自动跳过
也没什么人用所以懒得修了
你可以往数据根目录里随便丢一个wav解决这个问题，你也可以参考文档自行抽取验证集
其他部分应该没有什么跑不通的，如果有的话可以贴一下报错

**Comment by nellbekim** [comment]
![화면 캡처 2023-04-14 211252](https://user-images.githubusercontent.com/130500773/232040608-dbeffa38-1f72-4dc2-931a-d4219fcddf56.png)
What should I do?

**Comment by KakaruHayate** [comment]
> ![화면 캡처 2023-04-14 211252](https://user-images.githubusercontent.com/130500773/232040608-dbeffa38-1f72-4dc2-931a-d4219fcddf56.png) What should I do?
plz run again,it's maybe fix by https://github.com/yxlllc/DDSP-SVC/pull/28

**Comment by KakaruHayate** [comment]
[config.zip](https://github.com/yxlllc/DDSP-SVC/files/11420663/config.zip)

**Comment by kirbystudy** [comment]
> [![Open in Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/drive/1fK08FGlSwEduD9LDvrRJgkhYJPz37f6u?usp=sharing)

有推理版吗

**Comment by KakaruHayate** [comment]
> > > > [![Open in Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/drive/1fK08FGlSwEduD9LDvrRJgkhYJPz37f6u?usp=sharing)
> > > 
> > > 
> > > 有推理版吗
> > 
> > 
> > 我可以加一个
> 
> 好，谢谢大佬。


看了一下，DDSP现在的推理命令太复杂了。。。自己用命令改改吧

**Comment by kirbystudy** [comment]
> > > > > [![Open in Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/drive/1fK08FGlSwEduD9LDvrRJgkhYJPz37f6u?usp=sharing)
> > > > 
> > > > 
> > > > 有推理版吗
> > > 
> > > 
> > > 我可以加一个
> > 
> > 
> > 好，谢谢大佬。
> 
> 看了一下，DDSP现在的推理命令太复杂了。。。自己用命令改改吧

如果只推理的话，需要上传哪几个文件。

**Comment by KakaruHayate** [comment]
> > > > > > [![Open in Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/drive/1fK08FGlSwEduD9LDvrRJgkhYJPz37f6u?usp=sharing)
> > > > > 
> > > > > 
> > > > > 有推理版吗
> > > > 
> > > > 
> > > > 我可以加一个
> > > 
> > > 
> > > 好，谢谢大佬。
> > 
> > 
> > 看了一下，DDSP现在的推理命令太复杂了。。。自己用命令改改吧
> 
> 如果只推理的话，需要上传哪几个文件。

上传输入源的音频文件就可以了
你可以参考一下这个colab的推理部分
https://colab.research.google.com/drive/17PK5Vd-oyoxpsZ8nENktFcPZEwZmPrTb?usp=sharing

现在是否引入diff就多出一堆选项，不训练diff那些选项又是没用的，但写死了的话实际用的时候都得调，那还不如直接开个代码框把需要用的选项写上就完了

还是建议了解一下colab的文件结构，毕竟恢复备份之类的还是需要的

**Comment by kirbystudy** [comment]
> > > > > > > [![Open in Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/drive/1fK08FGlSwEduD9LDvrRJgkhYJPz37f6u?usp=sharing)
> > > > > > 
> > > > > > 
> > > > > > 有推理版吗
> > > > > 
> > > > > 
> > > > > 我可以加一个
> > > > 
> > > > 
> > > > 好，谢谢大佬。
> > > 
> > > 
> > > 看了一下，DDSP现在的推理命令太复杂了。。。自己用命令改改吧
> > 
> > 
> > 如果只推理的话，需要上传哪几个文件。
> 
> 上传输入源的音频文件就可以了 你可以参考一下这个colab的推理部分 https://colab.research.google.com/drive/17PK5Vd-oyoxpsZ8nENktFcPZEwZmPrTb?usp=sharing
> 
> 现在是否引入diff就多出一堆选项，不训练diff那些选项又是没用的，但写死了的话实际用的时候都得调，那还不如直接开个代码框把需要用的选项写上就完了
> 
> 还是建议了解一下colab的文件结构，毕竟恢复备份之类的还是需要的

谢谢大佬，我解决了可以推理了。

**Comment by eggtytw** [comment]
The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard
Reusing TensorBoard on port 6006 (pid 7368), started 0:03:10 ago. (Use '!kill 7368' to kill it.)
/content/DDSP-SVC
2023-06-23 13:22:57.041711: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-23 13:22:58.036721: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-06-23 13:23:00 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
 > config: configs/ddspsvc-contentvec768l12.yaml
 >    exp: exp/DDSPSVC-ContentVec-768l12
 [DDSP Model] Combtooth Subtractive Synthesiser
 [*] restoring model from exp/DDSPSVC-ContentVec-768l12/model_0.pt
Load all the data from : data/train
  0% 0/252 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/DDSP-SVC/train.py", line 89, in <module>
    loader_train, loader_valid = get_data_loaders(args, whole_audio=False)
  File "/content/DDSP-SVC/data_loaders.py", line 53, in get_data_loaders
    data_train = AudioDataset(
  File "/content/DDSP-SVC/data_loaders.py", line 143, in __init__
    raise ValueError(' [x] Muiti-speaker traing error : spk_id must be a positive integer from 1 to n_spk ')
ValueError:  [x] Muiti-speaker traing error : spk_id must be a positive integer from 1 to n_spk 

help :p

**Comment by KakaruHayate** [comment]
> The tensorboard extension is already loaded. To reload it, use: %reload_ext tensorboard Reusing TensorBoard on port 6006 (pid 7368), started 0:03:10 ago. (Use '!kill 7368' to kill it.) /content/DDSP-SVC 2023-06-23 13:22:57.041711: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations. To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags. 2023-06-23 13:22:58.036721: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT 2023-06-23 13:23:00 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
> 
> > config: configs/ddspsvc-contentvec768l12.yaml
> > exp: exp/DDSPSVC-ContentVec-768l12
> > [DDSP Model] Combtooth Subtractive Synthesiser
> > [*] restoring model from exp/DDSPSVC-ContentVec-768l12/model_0.pt
> > Load all the data from : data/train
> > 0% 0/252 [00:00<?, ?it/s]
> > Traceback (most recent call last):
> > File "/content/DDSP-SVC/train.py", line 89, in 
> > loader_train, loader_valid = get_data_loaders(args, whole_audio=False)
> > File "/content/DDSP-SVC/data_loaders.py", line 53, in get_data_loaders
> > data_train = AudioDataset(
> > File "/content/DDSP-SVC/data_loaders.py", line 143, in **init**
> > raise ValueError(' [x] Muiti-speaker traing error : spk_id must be a positive integer from 1 to n_spk ')
> > ValueError:  [x] Muiti-speaker traing error : spk_id must be a positive integer from 1 to n_spk
> 
> help :p

In notebook，only supports file structures with multiple speakers 

Like this

```
# training dataset
# the 1st speaker
data/train/audio/1/aaa.wav
data/train/audio/1/bbb.wav
...
# the 2nd speaker
data/train/audio/2/ccc.wav
data/train/audio/2/ddd.wav
...

# validation dataset
# the 1st speaker
data/val/audio/1/eee.wav
data/val/audio/1/fff.wav
...
# the 2nd speaker
data/val/audio/2/ggg.wav
data/val/audio/2/hhh.wav
...
```

**Comment by mcoi-dev** [comment]
> [![Open in Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/drive/1fK08FGlSwEduD9LDvrRJgkhYJPz37f6u?usp=sharing)

大佬，有4.0的吗？
