### ISSUE TITLE
diff模型保存问题

### ISSUE THREAD

**Issue by AlbieRWang** [yxlllc/DDSP-SVC#51]
大佬这个interval_force_save指的是保存最近2w的模型么，
现在diff模型只会保存一个是不是应该改成 interval_force_save==0
![image](https://github.com/yxlllc/DDSP-SVC/assets/28641863/03ec4c5c-1dd2-4027-82e0-19e6db28bf8d)
![image](https://github.com/yxlllc/DDSP-SVC/assets/28641863/d93f8d68-01eb-493e-82eb-e96dc981187d)

**Comment by AlbieRWang** [comment]
如果是间隔保存的话那没事了，是不是可以考虑保存最近多少步的功能

**Comment by yxlllc** [comment]
默认配置文件我调小到1万步强制保存了，保存最近多少步你觉得如果有必要加的话可以 pr
