### ISSUE TITLE
损失降到多少效果就可以了？

### ISSUE THREAD

**Issue by qiezikuangge** [yxlllc/DDSP-SVC#63]
大佬大佬，我训练的时候batch/s只有1左右，训练100000epochs太久了，而且用预训练模型的话，训练的loss基本都不会降了。。。

**Comment by yxlllc** [comment]
损失函数只是作为参考，训练到听起来效果不再改进即可。另外训练扩散模型比较容易过拟合（尽管损失函数可能看起来一切正常），因此建议实际推理不同训练程度的模型并互相比对
