### ISSUE TITLE
【DDSP + Diff-SVC 重构版】如何使用预训练声码器增强 DDSP 的输出结果，适配于更高的音域

### ISSUE THREAD

**Issue by hpx502766238** [yxlllc/DDSP-SVC#75]
如题，单独使用DDSP时使用enhancer_adaptive_key > 0 可将增强器适配于更高的音域，但是使用扩散模型+DDSP时应该如何实现音域扩展呢

**Comment by yxlllc** [comment]
很遗憾，由于算法原理完全不同，使用扩散模型时这个功能将丧失，目前我也没什么办法实现。。。
