### ISSUE TITLE
求助关于输出声音撕裂

### ISSUE THREAD

**Issue by mcoi-dev** [yxlllc/DDSP-SVC#76]
如题，训练了崩铁丹恒的模型[地址](https://pan.huang1111.cn/s/ePOZHg)

编码器：hubertsoft

F0：parselmouth

原音频：[水龙吟（UVR5人声）](https://pan.huang1111.cn/s/5Ylwtl)  ，变调2 ，输出音频：[](https://pan.huang1111.cn/s/vjOgFE)

请问如何解决（试过只用DDSP推理，直接电音了）？

**Comment by mcoi-dev** [comment]
纯DDSP推理音频：https://pan.huang1111.cn/s/4k74Hg

**Comment by yxlllc** [comment]
产生这个现象可能和数据，训练参数和推理参数等相关，我无法给出一个明确的结论

**Comment by mcoi-dev** [comment]
> 产生这个现象可能和数据，训练参数和推理参数等相关，我无法给出一个明确的结论

谢谢大佬，请问一下将模型保存频率降低（降到了100）会对训练有影响吗？数据集我已经确认过了，没有问题，也都格式化过了。或者将F0换成crepe会有所提升吗？

**Comment by mcoi-dev** [comment]
推理的时候我扩散都开到1000step了，跑了3个多小时

**Comment by yxlllc** [comment]
推理结果如果很奇怪可能和超出音域范围有关

**Comment by mcoi-dev** [comment]
> 推理结果如果很奇怪可能和超出音域范围有关

谢谢指点，ddsp换了naive也是一样，估计是音域问题。
