### ISSUE TITLE
关于webUI突然打不开了，一直显示loading？（The webUI won't open, it keeps showing loading.）

### ISSUE THREAD

**Issue by weco123** [yxlllc/DDSP-SVC#77]
正常成功运行了1周左右，一直能正常使用（成功训练+成功推理），但1个小时前突然webUI打不开了，一直显示loading，中间换了很多浏览器，关闭了所有浏览器插件，关闭了所有电脑软件以及杀毒软件，然后重启了好多次电脑都没有用。

I've been running it normally and successfully for about 1 week, and it's been working fine (successful training + successful reasoning), but 1 hour ago suddenly the webUI wouldn't open, it kept showing loading, and in between I switched browsers a lot, turned off all the browser plugins, turned off all the computer software as well as the antivirus software, and then restarted the computer many times to no avail.[](url)

**Comment by weco123** [comment]
![7650696b7dd6853d345470bdc7bbe79](https://github.com/yxlllc/DDSP-SVC/assets/101050044/29ef0453-8ccc-4c77-a0c1-9bd798563c90)

**Comment by weco123** [comment]
![image](https://github.com/yxlllc/DDSP-SVC/assets/101050044/127c7db9-cc45-4660-85f7-d1ef23ff1abc)

**Comment by mcoi-dev** [comment]
> 正常成功运行了1周左右，一直能正常使用（成功训练+成功推理），但1个小时前突然webUI打不开了，一直显示loading，中间换了很多浏览器，关闭了所有浏览器插件，关闭了所有电脑软件以及杀毒软件，然后重启了好多次电脑都没有用。
> 
> I've been running it normally and successfully for about 1 week, and it's been working fine (successful training + successful reasoning), but 1 hour ago suddenly the webUI wouldn't open, it kept showing loading, and in between I switched browsers a lot, turned off all the browser plugins, turned off all the computer software as well as the antivirus software, and then restarted the computer many times to no avail.

清除浏览器缓存，不要开梯子什么的，正常来说就可以了，如果实在连不上也不是不可以用cmd

```bash
#预处理
./pythonenv/python.exe preprocess.py -c ./configs/xxx.yaml
#DDSP
./pythonenv/python.exe train.py -c ./configs/xxx.yaml
#Diff
./pythonenv/python.exe train_diff.py -c ./configs/xxx/yaml
```
