### ISSUE TITLE
error while starting training

### ISSUE THREAD

**Issue by clashai** [yxlllc/DDSP-SVC#79]
File "D:\New folder (4)\DDSP-SVC\diffusion\data_loaders.py", line 202, in __getitem__
    if data_buffer['duration'] < (self.waveform_sec + 0.1):
RecursionError: maximum recursion depth exceeded in comparison

**Comment by yxlllc** [comment]
Check if the training set and validation set are placed correctly and the preprocessing is completed normally

**Comment by clashai** [comment]
Everything is normal i have a dataset of 13 mins good quality i split that into 2sec clips and for val i put 10 clips each 2secs long preprocessing is completely normal

**Comment by yxlllc** [comment]
2s is too short.
